### ISSUE TITLE
Add easy way to constantly upload new file

### ISSUE THREAD

**Issue by Scarladore** [GalaxyMaster2/bs-parity#20]
When using this app, I often am uploading a new file constantly and it is frustrating to have to refresh the app every time I need to do this. Having a place on the page, like at the top beside the page title, to drag a new file in would be very helpful

**Comment by nathancartlidge** [comment]
Do you think keeping drag+drop enabled when a map is loaded would be an intuitive enough way of achieving this, or would you prefer an actual button to take you back to the first page?

**Comment by Scarladore** [comment]
Honestly, that is the first thing I tried to do. I tried to drag a new file to the screen where the map was already loaded. But I am a UI dev as my day job so I'm not sure if its something normal everyday users would intuitively be able to notice. 
Maybe add a little note somewhere that tells users they can keep drag+dropping?

**Comment by nathancartlidge** [comment]
Sorry for the delay in getting back to you about this:

the dev branch version of bs-parity now supports this functionality - just drag a file onto the window and it should update with the new map

I'm working on a hotfix for master now, but that will take slightly longer to review and implement
